### ISSUE TITLE
Event management Kafka issues processing inbound events

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere#828] opened 2020-06-20 01:14 UTC
Hello, now it seems that there is no subscription to the Instance-Management Kafka message in event-Management, and the query to inboundEventsConsumer is not instantiated. After I added the instantiation, the subscription arrived, but I reported another error, what caused this error.

![1592615852(1)](https://user-images.githubusercontent.com/63097736/85188196-73478080-b2d7-11ea-8ebb-9c702cb6d56a.jpg)

![1592615887(1)](https://user-images.githubusercontent.com/63097736/85188202-79d5f800-b2d7-11ea-91ab-432e94d9bc38.jpg)

A new error
![1592615916(1)](https://user-images.githubusercontent.com/63097736/85188204-7d697f00-b2d7-11ea-9b74-e7e0ebb1cac4.jpg)

![1592615939(1)](https://user-images.githubusercontent.com/63097736/85188206-7f334280-b2d7-11ea-82d1-0791aef08433.jpg)

Thank you for your answer

**Comment by derekadams** [comment] 2020-06-23 23:28
This has been confirmed as a bug in the SiteWhere 3.0 code base and is probably also an issue in 2.x. We will fix the issue in 3.0 and possibly backport the fix to 2.x if applicable. Thanks!

**Comment by derekadams** [comment] 2020-06-23 23:31
This is a duplicate of #824

**Closed by derekadams** 2020-06-23 23:31 UTC
Labels: bug, duplicate
