### ISSUE TITLE
GDecodedEventPayload is misused as GPreprocessedEventPayload?

### ISSUE THREAD

**Issue by guofengzh** [sitewhere/sitewhere#824] opened 2020-06-10 13:35 UTC
The inbound processing service produces data of the type GDecodedEventPayload, but the event management service consumes it as that of the type GPreprocessedEventPayload. see [here](https://github.com/sitewhere/sitewhere/blob/master/service-inbound-processing/src/main/java/com/sitewhere/inbound/processing/InboundPayloadProcessingLogic.java#L119) and [here](https://github.com/sitewhere/sitewhere/blob/master/service-event-management/src/main/java/com/sitewhere/microservice/kafka/InboundEventsConsumer.java#L102).

It appears in master, 2.1.0, and 2.1.1 braches, so I am confused that I migth miss something so that I mis-understand the codes.

Your advice is appreciated.

**Comment by derekadams** [comment] 2020-06-23 23:32
This has been confirmed as a bug in the 3.0 code base. We will add a fix and backport to 2.x if applicable.

**Comment by derekadams** [comment] 2020-06-26 13:58
This is fixed for SiteWhere 3.0. The backport to 2.x will take some effort since 3.0 uses Kafka Streams and 2.x does not.

**Comment by ATM006** [comment] 2020-06-26 16:01
We used a similar approach to repair in 2.1.1,The problem【You must provide credentials to perform this action】 is still unsolvable。Can you tell me the logic of reporting measurement data and how to obtain verification information。
![image](https://user-images.githubusercontent.com/24607498/85875770-51825800-b807-11ea-9744-2ab76c00b432.png)

**Comment by ATM006** [comment] 2020-06-26 16:01
This is my test result。

![1234](https://user-images.githubusercontent.com/24607498/85877202-5e07b000-b809-11ea-93a7-4e24b8ada504.png)


2020-06-26 15:32:26.462 ERROR 1 --- [afka Consumer 1] c.s.m.kafka.InboundEventsConsumer        : Inbound processing for event batch failed.

com.sitewhere.spi.SiteWhereSystemException: You must provide credentials to perform this action.
        at com.sitewhere.security.UserContextManager.getCurrentTenant(UserContextManager.java:57) ~[sitewhere-core-2.1.0.jar!/:na]
        at com.sitewhere.grpc.client.device.CachedDeviceManagementApiChannel.getDeviceAssignment(CachedDeviceManagementApiChannel.java:281) ~[sitewhere-grpc-client-2.1.0.jar!/:na]
        at com.sitewhere.event.persistence.mongodb.MongoDeviceEventManagement.assertDeviceAssignmentById(MongoDeviceEventManagement.java:455) ~[classes!/:na]
        at com.sitewhere.event.persistence.mongodb.MongoDeviceEventManagement.addDeviceMeasurements(MongoDeviceEventManagement.java:200) ~[classes!/:na]
        at com.sitewhere.event.DeviceEventManagementDecorator.addDeviceMeasurements(DeviceEventManagementDecorator.java:88) ~[classes!/:na]
        at com.sitewhere.microservice.kafka.KafkaEventPersistenceTriggers.addDeviceMeasurements(KafkaEventPersistenceTriggers.java:70) ~[classes!/:na]
        at com.sitewhere.microservice.kafka.InboundEventsConsumer.storeEvents(InboundEventsConsumer.java:137) ~[classes!/:na]
        at com.sitewhere.microservice.kafka.InboundEventsConsumer.process(InboundEventsConsumer.java:110) ~[classes!/:na]
        at com.sitewhere.microservice.kafka.MicroserviceKafkaConsumer$MessageConsumer.run(MicroserviceKafkaConsumer.java:148) [sitewhere-microservice-2.1.0.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

**Comment by ATM006** [comment] 2020-06-26 16:03
In addition, it is not recommended to close the problem before the fatal problem is fixed to avoid losing the problem.
Thank you very much！

**Comment by derekadams** [comment] 2020-06-26 16:10
Sorry about that. This is fixed for the `sitewhere-3.0.0` branch, but hasn't been fixed for 2.x. The issue with not having user context can probably be addressed by running the code that calls the external microservice in a [`SystemUserRunnable`](https://github.com/sitewhere/sitewhere/blob/master/sitewhere-microservice/src/main/java/com/sitewhere/microservice/security/SystemUserRunnable.java#L26). That will add the permissions of the "system" user to the call, which will allow it to query via gRPC.

**Comment by ATM006** [comment] 2020-06-27 01:43
@derekadams Thank you very much！Will you fix this problem for 2.x recently?Eagerly waiting

**Comment by ATM006** [comment] 2020-06-29 14:56
For the known problems in sitewhere2. X, we have made the following modifications, which may help solve the problems. Thank you very much.
https://github.com/sitewhere/sitewhere/compare/sitewhere-2.1.1...ATM006:sitewhere-2.1.1?expand=1

**Closed** 2020-08-07 21:36 UTC
Labels: bug/critical
